name: PHP Quality Assurance
on: [ push, pull_request ]
jobs:

    Unit_Tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'no unit tests') }}
        strategy:
            matrix:
                php: [ '7.2', '7.3', '7.4' ]

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Check syntax error in sources
                run: find ./src/ ./inc/ ./tests/src/ ./tests/unit/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

            -   name: Remove Psalm before tests, to prevent installation conflicts
                run: composer.phar remove vimeo/psalm --no-update

            -   name: Install dependencies
                uses: "ramsey/composer-install@v1"

            -   name: Run unit tests
                run: ./vendor/bin/phpunit

    Static_Analisys:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'no static qa') }}
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'

            -   name: Install dependencies
                uses: "ramsey/composer-install@v1"

            -   name: Check code styles
                run: ./vendor/bin/phpcs

            -   name: Check cross-version PHP compatibility
                run: composer phpcompat

            -   name: Check Psalm
                run: ./vendor/bin/psalm --no-cache --output-format=github
