name: PHP Quality Assurance
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        strategy:
            matrix:
                php-versions: ['7.2', '7.3', '7.4']
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}

            -   name: Check syntax error in sources
                run: find ./src/ ./tests/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

            -   name: Install dependencies
                run: composer install -q -n -a --no-progress --prefer-dist

            -   name: Run unit tests
                run: ./vendor/bin/phpunit --testsuite=unit --no-coverage

            -   name: Check code styles
                run: ./vendor/bin/phpcs

            -   name: Check Psalm
                run: ./vendor/bin/psalm --show-info=false --no-progress --output-format=compact
